[package]
name = "jp2k"
version = "0.1.0"
authors = ["Jacob Brown <kardeiz@gmail.com>", "Leo Schwarz <mail@leoschwarz.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
image = "0.22"
libc = "0.2"
openjpeg-sys = { path = "openjpeg-sys", version = "0.1.0" }

